name: Cicd

on:
  push:
    branches: [ '*' ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: Build
        run: |
          yarn
          yarn buildOnce
          
      - name: Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: buildResults
          path: |
            buildResults
